
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.froi.generadorfiguras.analizadores.capas;

/** CUP generated class containing symbol constants. */
public class ParserCapasSym {
  /* terminals */
  public static final int COLOR = 8;
  public static final int COMA = 7;
  public static final int PUNTO_COMA = 6;
  public static final int EOF = 0;
  public static final int LLAVE_C = 5;
  public static final int LLAVE_A = 4;
  public static final int NUMERO = 3;
  public static final int error = 1;
  public static final int ALFANUMERICO = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ALFANUMERICO",
  "NUMERO",
  "LLAVE_A",
  "LLAVE_C",
  "PUNTO_COMA",
  "COMA",
  "COLOR"
  };
}

