/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.froi.generadorfiguras.frontend;

import com.froi.generadorfiguras.estructuras.ListaDoblementeEnlazada;
import com.froi.generadorfiguras.estructuras.MatrizDispersa;
import com.froi.generadorfiguras.manejadores.*;
import com.froi.generadorfiguras.nodos.NodoAVL;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author froi-pc
 */
public class VentanaInicial extends javax.swing.JFrame {

    private ManejadorPrincipal manejadorPrincipal;
    private ManejadorArchivos manejadorArchivos;
    private ManejadorGraficas manejadorGraficas;
    
    /**
     * Creates new form VentanaInicial
     */
    public VentanaInicial() {
        initComponents();
        this.manejadorPrincipal = new ManejadorPrincipal();
        this.manejadorArchivos = new ManejadorArchivos();
        this.manejadorGraficas = new ManejadorGraficas();
        lblBuscar.setVisible(false);
        lblApoyo2.setVisible(false);
        txtApoyo2.setVisible(false);
        txtBuscar.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnCapas = new javax.swing.JButton();
        btnImagenes = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCapas = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtUsuarios = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtImagenes = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboTipoGrafica = new javax.swing.JComboBox<>();
        btnGraficar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        lblBuscar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        comboTipoGeneracion = new javax.swing.JComboBox<>();
        lblDescripcionGraficacion = new javax.swing.JLabel();
        txtApoyoImagenes = new javax.swing.JTextField();
        lblTipoRecorrido = new javax.swing.JLabel();
        comboTipoRecorrido = new javax.swing.JComboBox<>();
        btnGenerarImagen = new javax.swing.JButton();
        lblApoyo2 = new javax.swing.JLabel();
        txtApoyo2 = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 738, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCapas.setBackground(new java.awt.Color(207, 207, 207));
        btnCapas.setText("Capas");
        btnCapas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapasActionPerformed(evt);
            }
        });

        btnImagenes.setBackground(new java.awt.Color(207, 207, 207));
        btnImagenes.setText("Imagenes");
        btnImagenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagenesActionPerformed(evt);
            }
        });

        btnUsuarios.setBackground(new java.awt.Color(207, 207, 207));
        btnUsuarios.setText("Usuarios");
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });

        txtCapas.setColumns(20);
        txtCapas.setRows(5);
        jScrollPane1.setViewportView(txtCapas);

        txtUsuarios.setColumns(20);
        txtUsuarios.setRows(5);
        jScrollPane2.setViewportView(txtUsuarios);

        txtImagenes.setColumns(20);
        txtImagenes.setRows(5);
        jScrollPane3.setViewportView(txtImagenes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(btnCapas, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnImagenes, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCapas)
                    .addComponent(btnUsuarios)
                    .addComponent(btnImagenes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Carga de Archivos", jPanel1);

        jPanel6.setBackground(new java.awt.Color(254, 254, 254));
        jPanel6.setPreferredSize(new java.awt.Dimension(548, 548));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setText("Tipo de Grafica");

        comboTipoGrafica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lista de Imagenes", "Arbol de Capas", "Capa", "Imagen y Arbol de Capas", "Arbol de Usuarios" }));
        comboTipoGrafica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoGraficaActionPerformed(evt);
            }
        });

        btnGraficar.setText("Graficar");
        btnGraficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficarActionPerformed(evt);
            }
        });

        lblBuscar.setText("Buscar");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboTipoGrafica, 0, 265, Short.MAX_VALUE)
                    .addComponent(txtBuscar)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lblBuscar))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnGraficar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboTipoGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGraficar)
                        .addGap(0, 427, Short.MAX_VALUE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Estado de Memoria", jPanel5);

        jPanel4.setBackground(new java.awt.Color(254, 254, 254));
        jPanel4.setPreferredSize(new java.awt.Dimension(548, 548));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
        );

        jLabel2.setText("Tipo de Generación:");

        comboTipoGeneracion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Recorrido Limitado", "Lista de Imagenes", "Capa", "Usuario" }));
        comboTipoGeneracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoGeneracionActionPerformed(evt);
            }
        });

        lblDescripcionGraficacion.setText("Numero de Capas:");

        lblTipoRecorrido.setText("Tipo de Recorrido:");

        comboTipoRecorrido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inorden", "Preorden", "Postorden" }));
        comboTipoRecorrido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoRecorridoActionPerformed(evt);
            }
        });

        btnGenerarImagen.setText("Generar Imagen");
        btnGenerarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarImagenActionPerformed(evt);
            }
        });

        lblApoyo2.setText("Id de Imagen:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblApoyo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtApoyo2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboTipoGeneracion, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtApoyoImagenes, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboTipoRecorrido, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGenerarImagen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDescripcionGraficacion, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTipoRecorrido, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 75, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)))
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboTipoGeneracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDescripcionGraficacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApoyoImagenes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTipoRecorrido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboTipoRecorrido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblApoyo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApoyo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGenerarImagen)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Imagenes", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCapasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapasActionPerformed
        // TODO add your handling code here:
        
        JFileChooser fileChooser = new JFileChooser();
        //Indicamos que solo podemos seleccionar archivos
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        //Indicamos el filtro .form
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.cap", "cap");
        fileChooser.setFileFilter(filtro);
        //Abrimos el file chooser
        int comprobante = fileChooser.showOpenDialog(fileChooser);
        if(comprobante == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
            txtCapas.setText("Se seleccionó el archivo a importar\n");
            //Enviamos a analizar el archivo a importar
            manejadorArchivos.manejarArchivoCap(archivo, manejadorPrincipal.getArbolCapas());
        } else {
            txtCapas.setText("Error al seleccionar el archivo a importar\n");
        }
        
    }//GEN-LAST:event_btnCapasActionPerformed

    private void btnImagenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagenesActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        //Indicamos que solo podemos seleccionar archivos
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        //Indicamos el filtro .form
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.im", "im");
        fileChooser.setFileFilter(filtro);
        //Abrimos el file chooser
        int comprobante = fileChooser.showOpenDialog(fileChooser);
        if(comprobante == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
            txtImagenes.setText("Se seleccionó el archivo a importar\n");
            //Enviamos a analizar el archivo a importar
            manejadorArchivos.manejarArchivoIm(archivo, manejadorPrincipal.getListaImagenes(), manejadorPrincipal.getArbolCapas());
        } else {
            txtImagenes.setText("Error al seleccionar el archivo a importar\n");
        }
    }//GEN-LAST:event_btnImagenesActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        //Indicamos que solo podemos seleccionar archivos
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        //Indicamos el filtro .form
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("*.usr", "usr");
        fileChooser.setFileFilter(filtro);
        //Abrimos el file chooser
        int comprobante = fileChooser.showOpenDialog(fileChooser);
        if(comprobante == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
            txtUsuarios.setText("Se seleccionó el archivo a importar\n");
            //Enviamos a analizar el archivo a importar
            manejadorArchivos.manejarArchivoUsr(archivo, manejadorPrincipal.getArbolUsuarios(), manejadorPrincipal.getListaImagenes());
        } else {
            txtUsuarios.setText("Error al seleccionar el archivo a importar\n");
        }
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnGraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficarActionPerformed
        // TODO add your handling code here:
        switch (comboTipoGrafica.getSelectedIndex()) {
            case 0:
                manejadorGraficas.graficarEstadoMemoria(manejadorPrincipal.getListaImagenes().dotCode(), "ListaImagenes");
                break;
            case 1:
                manejadorGraficas.graficarEstadoMemoria(manejadorPrincipal.getArbolCapas().dotCode(), "ArbolCapas");
                break;
            case 2:
                NodoAVL capaBuscada;
                String capaABuscar = txtBuscar.getText();
                if((capaBuscada = manejadorPrincipal.getArbolCapas().buscar(capaABuscar)) != null) {
                    MatrizDispersa matrizObtenida = (MatrizDispersa) capaBuscada.getContenido();
                    manejadorGraficas.graficarEstadoMemoria(matrizObtenida.dotCode(), "CapaSolicitada");
                } else {
                    JOptionPane.showMessageDialog(null, "No se encontró la capa " + capaABuscar);
                }
                break;
            case 3:
                break;
            case 4:
                manejadorGraficas.graficarEstadoMemoria(manejadorPrincipal.getArbolUsuarios().dotCode(), "ArbolUsuarios");
                break;
            default:
                break;
        }
    }//GEN-LAST:event_btnGraficarActionPerformed

    private void comboTipoGraficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoGraficaActionPerformed
        // TODO add your handling code here:
        switch(comboTipoGrafica.getSelectedIndex()) {
            case 0:
                lblBuscar.setVisible(false);
                txtBuscar.setVisible(false);
                break;
            case 1:
                lblBuscar.setVisible(false);
                txtBuscar.setVisible(false);
                break;
            case 2:
                lblBuscar.setVisible(true);
                txtBuscar.setVisible(true);
                break;
            case 3:
                lblBuscar.setVisible(true);
                txtBuscar.setVisible(true);
                break;
            case 4:
                lblBuscar.setVisible(false);
                txtBuscar.setVisible(false);
                break;
            default:
                lblBuscar.setVisible(false);
                txtBuscar.setVisible(false);
                break;
        }
    }//GEN-LAST:event_comboTipoGraficaActionPerformed

    private void comboTipoRecorridoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoRecorridoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTipoRecorridoActionPerformed

    private void comboTipoGeneracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoGeneracionActionPerformed
        // TODO add your handling code here:
        switch(comboTipoGeneracion.getSelectedIndex()) {
            case 0:
                lblDescripcionGraficacion.setText("Numero de Capas a Utilizar: ");
                lblApoyo2.setVisible(false);
                txtApoyo2.setVisible(false);
                lblTipoRecorrido.setVisible(true);
                comboTipoRecorrido.setVisible(true);
                break;
            case 1:
                lblDescripcionGraficacion.setText("Id de la Imagen: ");
                lblApoyo2.setVisible(false);
                txtApoyo2.setVisible(false);
                lblTipoRecorrido.setVisible(false);
                comboTipoRecorrido.setVisible(false);
                break;
            case 2:
                lblDescripcionGraficacion.setText("Id de la Capa: ");
                lblApoyo2.setVisible(false);
                txtApoyo2.setVisible(false);
                lblTipoRecorrido.setVisible(false);
                comboTipoRecorrido.setVisible(false);
                break;
            case 3:
                lblDescripcionGraficacion.setText("Id del Usuario: ");
                lblApoyo2.setVisible(true);
                txtApoyo2.setVisible(true);
                lblTipoRecorrido.setVisible(false);
                comboTipoRecorrido.setVisible(false);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_comboTipoGeneracionActionPerformed

    private void btnGenerarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarImagenActionPerformed
        // TODO add your handling code here:
        switch(comboTipoGeneracion.getSelectedIndex()) {
            case 0:
                //Por recorrido limitado
                break;
            case 1:
                //Por lista de imagenes
                break;
            case 2:
                //Por capa
                String capaSolicitada = txtApoyoImagenes.getText();
                NodoAVL capaGraficar;
                if((capaGraficar = manejadorPrincipal.getArbolCapas().buscar(capaSolicitada)) != null) {
                    ListaDoblementeEnlazada listaCapasGraficar = new ListaDoblementeEnlazada();
                    listaCapasGraficar.insertar(capaGraficar);
                    manejadorGraficas.graficarImagen(listaCapasGraficar, jPanel4);
                    JOptionPane.showMessageDialog(null, "Capa " + capaSolicitada + " encontrada");
                } else {
                    JOptionPane.showMessageDialog(null, "No se ha encontrado la capa: "  + capaSolicitada);
                }
                break;
            case 3:
                //Por Lista de Imagenes
                break;
            default:
                break;
        }
    }//GEN-LAST:event_btnGenerarImagenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapas;
    private javax.swing.JButton btnGenerarImagen;
    private javax.swing.JButton btnGraficar;
    private javax.swing.JButton btnImagenes;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JComboBox<String> comboTipoGeneracion;
    private javax.swing.JComboBox<String> comboTipoGrafica;
    private javax.swing.JComboBox<String> comboTipoRecorrido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblApoyo2;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblDescripcionGraficacion;
    private javax.swing.JLabel lblTipoRecorrido;
    private javax.swing.JTextField txtApoyo2;
    private javax.swing.JTextField txtApoyoImagenes;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextArea txtCapas;
    private javax.swing.JTextArea txtImagenes;
    private javax.swing.JTextArea txtUsuarios;
    // End of variables declaration//GEN-END:variables
}
