
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.froi.generadorfiguras.analizadores.imagenes;

/** CUP generated class containing symbol constants. */
public class ParserImagenesSym {
  /* terminals */
  public static final int NUMERO = 5;
  public static final int COMA = 4;
  public static final int error = 1;
  public static final int ALFANUMERICO = 6;
  public static final int LLAVE_C = 3;
  public static final int EOF = 0;
  public static final int LLAVE_A = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LLAVE_A",
  "LLAVE_C",
  "COMA",
  "NUMERO",
  "ALFANUMERICO"
  };
}

